// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

type IndexedDatum struct {
	ID        int32
	PublicKey string
	FromValue int32
	ToValue   int32
	Role      string
	Signers   []int32
	Signature string
	Round     int32
	Root      []int32
	Height    int32
}
