// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package db

import (
	"context"
)

const createIndexedData = `-- name: CreateIndexedData :exec
INSERT INTO indexed_data (public_key, from_value, to_value, role, signers, signature, round, root, height)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
		ON CONFLICT (public_key, from_value, to_value, role, height, round) DO UPDATE SET
			signers = EXCLUDED.signers,
			signature = EXCLUDED.signature,
			root = EXCLUDED.root
`

type CreateIndexedDataParams struct {
	PublicKey string
	FromValue int32
	ToValue   int32
	Role      string
	Signers   []int32
	Signature string
	Round     int32
	Root      []int32
	Height    int32
}

func (q *Queries) CreateIndexedData(ctx context.Context, arg CreateIndexedDataParams) error {
	_, err := q.db.Exec(ctx, createIndexedData,
		arg.PublicKey,
		arg.FromValue,
		arg.ToValue,
		arg.Role,
		arg.Signers,
		arg.Signature,
		arg.Round,
		arg.Root,
		arg.Height,
	)
	return err
}
